management:
  security:
    enabled: false
  server:
    port: 7777
    base-path: /management
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    probes:
      enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'
      
server:
    shutdown: GRACEFUL
    http2:
     enabled: true
    port: 3050
   

      
spring:
  main:
    allow-circular-references: false
    lazy-initialization: false
  application:
    name: people   

  data:
    mongodb:
     # uri: mongodb://armdev:armdev3000@localhost:27017/peopleDB?ssl=false&connectTimeoutMS=300000&minPoolSize=0&maxPoolSize=500&maxIdleTimeMS=900000&readPreference=primary&authSource=admin    
    # uri: mongodb://armdev:armdev3000@localhost:27017/peopleDB?authSource=admin&mechanism=SCRAM-SHA-256
      ##uri: mongodb://admin:admin@localhost:27017/peopleDB?replicaSet=rs0&authSource=admin&readPreference=primary
      uri: mongodb://root:password123@localhost:27017,localhost:27018,localhost:27019,localhost:27020/peopleDB?replicaSet=rs0&authSource=admin
      authentication-database: admin

