management:
  security:
    enabled: false
  server:
    port: 7777
    base-path: /management
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    probes:
      enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'
      
server:
    shutdown: GRACEFUL
    http2:
     enabled: true
    port: 3050
   

      
spring:
  main:
    allow-circular-references: false
    lazy-initialization: false
  application:
    name: people   

  data:
    mongodb:
      host: localhost
      port: 27017
      database: peopleDB
      #username: ${MONGO_USERNAME}
     # password: ${MONGO_PASSWORD}
      authentication-database: admin
      auto-index-creation: true

