management:
  security:
    enabled: false
  server:
    port: 7050
    base-path: /management
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    probes:
      enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'
      
server:
    tomcat:        
      connection-timeout: 20m
      keep-alive-timeout: 20m
    shutdown: GRACEFUL
    http2:
     enabled: true
    port: 7025
    servlet:
      session:
        timeout: 10m
    compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/svg+xml     
      min-response-size: 1024

      
spring:    
  thread:
    virtual:
      enabled: true
  main:
    allow-circular-references: false
    lazy-initialization: false
  application:
    name: people

  data:
    mongodb:
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: admin     
      uri: ${MONGO_URI}

